### ISSUE TITLE
Is latest version `0.1.5` or `0.1.6`?

### ISSUE THREAD

**Issue by tukusejssirs** [microud/nest-mqtt#12]
In [`package.json`](https://github.com/microud/nest-mqtt/blob/master/package.json#L3), you have `0.1.5`, but on [NPM](https://www.npmjs.com/package/nest-mqtt) it says `0.1.6`.

I suspect that you are not updating the version in `package.json` and `package-lock.json` in `master` after you release a new NPM version.

**Comment by microud** [comment]
I have published as version 0.1.7.
