### ISSUE TITLE
issue in nestjs 8

### ISSUE THREAD

**Issue by ivanlunardi** [microud/nest-mqtt#8]
can't use in newest version 

ERROR [ExceptionHandler] Nest can't resolve dependencies of the MqttExplorer (DiscoveryService, MetadataScanner, MQTT_LOGGER_PROVIDER, ?, MQTT_CLIENT_INSTANCE, MQTT_OPTION_PROVIDER). Please make sure that the argument Reflector at index [3] is available in the MqttModule context.

Potential solutions:
- If Reflector is a provider, is it part of the current MqttModule?
- If Reflector is exported from a separate @Module, is that module imported within MqttModule?
  @Module({
    imports: [ /* the Module containing Reflector */ ]
  })

**Comment by fjc2112** [comment]
Same here

**Comment by microud** [comment]
#13
